<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menu_items')->insert([
            [
                'id' => 2,
                'name' => 'EGG & GREENS WHOLE GRAIN',
                'description' => 'A wholesome sandwich with fluffy egg and fresh greens...',
                'category_id' => 2,
                'image_url' => 'storage/products/sandwich1.png',
                'carb' => '38g',
                'protein' => '16g',
                'fat' => '12g',
                'calories' => '±320 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'name' => 'BERRY BLISS',
                'description' => 'Fresh strawberries and coconut flakes over creamy yogurt...',
                'category_id' => 3,
                'image_url' => 'storage/products/dessert.png',
                'carb' => '26g',
                'protein' => '9g',
                'fat' => '8g',
                'calories' => '±210 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'name' => 'SUMMER BERRY BREEZE',
                'description' => 'Berry-infused sparkling water with fruit slices...',
                'category_id' => 4,
                'image_url' => 'storage/products/splash1.png',
                'carb' => '14g',
                'protein' => '0g',
                'fat' => '0g',
                'calories' => '±60 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'name' => 'Salad buah',
                'description' => 'Makanan sehat dan kenyang',
                'category_id' => 1,
                'image_url' => 'storage/products/salad1.png',
                'carb' => '100g',
                'protein' => '100g',
                'fat' => '100g',
                'calories' => '100 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'name' => 'Avocado Toast',
                'description' => 'Mashed avocado on toasted artisan bread with a sprinkle of chili flakes.',
                'category_id' => 2,
                'image_url' => 'storage/products/sandwich2.png',
                'carb' => '30g',
                'protein' => '8g',
                'fat' => '18g',
                'calories' => '±300 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'name' => 'Quinoa Salad Bowl',
                'description' => 'Healthy quinoa with roasted vegetables and lemon vinaigrette.',
                'category_id' => 1,
                'image_url' => 'storage/products/salad2.png',
                'carb' => '45g',
                'protein' => '12g',
                'fat' => '15g',
                'calories' => '±380 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'name' => 'Matcha Latte',
                'description' => 'Premium matcha green tea with steamed almond milk.',
                'category_id' => 4,
                'image_url' => 'storage/products/smoothies1.png',
                'carb' => '18g',
                'protein' => '4g',
                'fat' => '3g',
                'calories' => '±120 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'name' => 'Grilled Chicken Wrap',
                'description' => 'Lean grilled chicken, fresh veggies, and light yogurt dressing in a whole wheat wrap.',
                'category_id' => 2,
                'image_url' => 'storage/products/sandwich3.png',
                'carb' => '40g',
                'protein' => '32g',
                'fat' => '14g',
                'calories' => '±410 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'name' => 'Fruit Parfait',
                'description' => 'Layers of greek yogurt, granola, and mixed seasonal berries.',
                'category_id' => 3,
                'image_url' => 'storage/products/dessert.png',
                'carb' => '35g',
                'protein' => '15g',
                'fat' => '5g',
                'calories' => '±250 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'name' => 'Iced Cold Brew',
                'description' => 'Smooth, slow-steeped cold brew coffee served over ice.',
                'category_id' => 4,
                'image_url' => 'storage/products/drink.png',
                'carb' => '0g',
                'protein' => '0g',
                'fat' => '0g',
                'calories' => '±5 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'name' => 'Caesar Salad',
                'description' => 'Crisp romaine lettuce, parmesan cheese, croutons, and Caesar dressing.',
                'category_id' => 1,
                'image_url' => 'storage/products/salad3.png',
                'carb' => '20g',
                'protein' => '10g',
                'fat' => '25g',
                'calories' => '±350 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'name' => 'Chia Seed Pudding',
                'description' => 'Creamy coconut milk chia pudding topped with fresh mango.',
                'category_id' => 3,
                'image_url' => 'storage/products/dessert.png',
                'carb' => '25g',
                'protein' => '6g',
                'fat' => '12g',
                'calories' => '±220 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'name' => 'Turkey & Cheese Panini',
                'description' => 'Smoked turkey breast and melted provolone cheese on sourdough.',
                'category_id' => 2,
                'image_url' => 'storage/products/sandwich4.png',
                'carb' => '42g',
                'protein' => '28g',
                'fat' => '16g',
                'calories' => '±450 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'name' => 'Green Detox Smoothie',
                'description' => 'Blend of spinach, green apple, cucumber, and ginger.',
                'category_id' => 4,
                'image_url' => 'storage/products/smoothies2.png',
                'carb' => '32g',
                'protein' => '3g',
                'fat' => '1g',
                'calories' => '±140 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'name' => 'Mediterranean Chickpea Salad',
                'description' => 'Chickpeas, cucumbers, cherry tomatoes, and feta cheese with olive oil.',
                'category_id' => 1,
                'image_url' => 'storage/products/salad4.png',
                'carb' => '35g',
                'protein' => '12g',
                'fat' => '16g',
                'calories' => '±320 Cal',
                'price' => rand(15000, 75000), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
